[project]
name = "caden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inspect-ai>=0.3.165",
    "modal>=1.3.1",
    "transformers>=4.57.6",
    "vllm>=0.14.1",
]